name: Java CI/CD with Maven - Build and Deploy WAR

on:
  push:
    branches: [ main, feature-hello ]
    paths:
      - 'src/main/java/com/example/HelloServlet.java'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Verify with Maven
      run: mvn clean verify -DskipTests
    - name: Build with Maven
      run: mvn package
    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: servlet-war
        path: target/*.war
        if-no-files-found: error

  deploy:
    runs-on: [self-hosted, windows] # Chạy trên self-hosted runner
    needs: build # Chạy sau job build
    steps:
    - name: Download WAR artifact
      uses: actions/download-artifact@v4
      with:
        name: servlet-war
        path: ./artifacts
    - name: Stop Tomcat
      run: |
        PowerShell -ExecutionPolicy Bypass -Command "if (Test-Connection -ComputerName localhost -TcpPort 8005 -Quiet -TimeoutSeconds 5) { if (Test-Path 'D:\Tomcat10\bin\shutdown.bat') { & 'D:\Tomcat10\bin\shutdown.bat' } } else { Write-Host 'Tomcat not running on port 8005, skipping shutdown.bat' }; Start-Sleep -Seconds 10; Get-Process -Name 'java' -ErrorAction SilentlyContinue | Where-Object { `$_.Path -like '*D:\Tomcat*' } | Stop-Process -Force -ErrorAction SilentlyContinue"
      shell: cmd
    - name: Deploy WAR to Tomcat
      run: |
        PowerShell -ExecutionPolicy Bypass -Command "Remove-Item -Path 'D:\Tomcat10\webapps\java-servlet-web-1.0-SNAPSHOT.war' -Force -ErrorAction SilentlyContinue; Remove-Item -Path 'D:\Tomcat10\webapps\java-servlet-web-1.0-SNAPSHOT' -Recurse -Force -ErrorAction SilentlyContinue; Copy-Item -Path '.\artifacts\java-servlet-web-1.0-SNAPSHOT.war' -Destination 'D:\Tomcat10\webapps' -Force"
      shell: cmd
    - name: Start Tomcat
      run: |
        PowerShell -ExecutionPolicy Bypass -Command "Start-Process -FilePath 'D:\Tomcat10\bin\startup.bat' -NoNewWindow -Wait"
      shell: cmd
    - name: Verify Deployment
      run: |
        PowerShell -ExecutionPolicy Bypass -Command "Start-Sleep -Seconds 60; `$status = Invoke-WebRequest -Uri 'http://localhost:8089/java-servlet-web-1.0-SNAPSHOT/hello' -UseBasicParsing -ErrorAction SilentlyContinue; if (`$status -and `$status.Content -like '*Hello, World*') { Write-Host 'Deployment successful!' } else { Write-Error 'Deployment failed. Check D:\Tomcat10\logs\catalina.out.'; exit 1 }}"
      shell: cmd