name: Java CI with Maven - Thử build

on:
  push:
    branches: [ main, "feature-*" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Thêm dòng này để có thể chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean package
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-build
        path: |
            target/*.jar
            target/*.war

